### ISSUE TITLE
File Put Contents LOCK_EX

### ISSUE THREAD

**Issue by nomadicjosh** [emsifa/laci-db#1]
I was looking at [line 420](https://github.com/emsifa/laci-db/blob/master/src/Collection.php#L420) in Collections, and saw that there was no LOCK_EX.

Are you handling file locking in a different way so that two people are not writing to the file at the same time?

**Comment by emsifa** [comment]
Sorry for late response.

No, I didn't think about file locking before. I will add this soon.

Thanks for your suggestion. :smiley:
