### ISSUE TITLE
Replace Method

### ISSUE THREAD

**Issue by nomadicjosh** [emsifa/laci-db#11]
Would it be possible to add a replace method that is similar to [this](https://stackoverflow.com/questions/29779985/php-find-and-replace-of-json-data)

**Comment by emsifa** [comment]
For now, it is possible using `map` method. 

It would be cool if we can do something like `$collection->replace($replacers)->get()`. But `replace` function in your link do recursive replace, and I think it is not common needs.

I will think another way to achieve this. Maybe using macro query(?), so we can add custom method as we needs.

**Comment by nomadicjosh** [comment]
Ok, so let's say I have a tags column in the database, and it has data like this `tags: php, git, npj`. There are several records that might have the tag `npj`, and it should be `npm`. So, how would I use the map method to do a replace?

I am pretty much thinking of a regex replace and not something like an update.

**Comment by emsifa** [comment]
If you want to replace a whole json (string), `map` is not your choice. And there is no way to do that with current APIs.

But if you just want to replace "npj" with "npm", you can use `map` like this:

For example your data is something like this:

```json
[
  {
    "_id": 1,
    "tags": ["php", "git", "npj"]
  },
  {
    "_id": 2,
    "tags": ["npj"]
  },
  {
    "_id": 3,
    "tags": ["npj"]
  }
]
```

Your `map` should be like this:

```php
$query = $collection->map(function($data) {

    $data['tags'] = array_map(function ($tag) { 
        return $tag == 'npj' ? 'npm' : $tag;
        //  Or if you want to use str_replace
        return str_replace('npj', 'npm', $tag);
    }, $data['tags']);

    return $data;
});

// If you want to save
$query->save();

// Or just get the result
$result = $query->get();
```

**Comment by nomadicjosh** [comment]
That's exactly what I need. Thank you!

**Comment by nomadicjosh** [comment]
Ok, so below is my code and it is not working. I am missing something, but can't see what it is:
```
    $collection = new Collection('db/post.json');
    $collection->begin();
    try {

        $collection->where('post_type.posttype_id', (int) $id)->map(function($data) use($old_slug, $new_slug) {

            $data['post_relative_url'] = array_map(function ($slug) use($old_slug, $new_slug) {
                return str_replace($old_slug, $new_slug, $slug);
            }, $data['post_relative_url']);

            return $data;
        });
        $collection->commit();
    } catch (Exception $ex) {
        $collection->rollback();
    }
```

**Comment by nomadicjosh** [comment]
I figured it out. I can't use `array_map()` because the field to update is a string and not an array, and I can't use transactions on mapping.
