### ISSUE TITLE
Composer Issue

### ISSUE THREAD

**Issue by nomadicjosh** [emsifa/laci-db#5]
Thanks for the new changes, however, I can't pull in your new v0.2.2 tag via composer. I also tried dev-master as well, but that did not work either.

This is the error I get:
```The requested package emsifa/laci ^0.2.2 exists as emsifa/laci[dev-master, v0.0.1, v0.0.2, v0.1.0, v0.1.1, v0.2.0] but these are rejected by your constraint.```

**Comment by emsifa** [comment]
Sorry, I didn't setup packagist service hooks before, so I need to manually update it on packagist.

Now you can install it.

If you still have this problem, try `composer clear-cache` then update/install again.

**Comment by nomadicjosh** [comment]
It worked, thank you.
