### ISSUE TITLE
Untracked Changes

### ISSUE THREAD

**Issue by nomadicjosh** [emsifa/laci-db#6]
I am managing a website of mine with git, and I am trying to push the new changes to my repository and I get the following issue:

```modified:   vendor/emsifa/laci (untracked content)```

This keeps me from pushing laci-db to my git repository.

**Comment by emsifa** [comment]
Sorry for late response, I have some deadline yesterday.

Are you using `"emsifa/laci": "dev-master"`in your `composer.json` file? if yes, this will tell composer to clone laci repository instead just put some files into vendor directory.

As this [composer page](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) said. For general recommendation, you should put `vendor` directory in `.gitignore` file. But if you really want to push vendor files, you can avoid gitsubmodule problem by install tagged version instead dev-master.

**Comment by nomadicjosh** [comment]
Not a problem. No, I am using the following: ```"emsifa/laci": "^0.2.2"```

I used the command ```composer require emsifa/laci```

**Comment by nomadicjosh** [comment]
But I was thinking the other day that I probably should .gitignore the vendor directory. So, that is what I will probably end up doing.
