### ISSUE TITLE
The IN Keyword

### ISSUE THREAD

**Issue by nomadicjosh** [emsifa/laci-db#7]
Trying to figure out how the IN keyword works.

Is it this:
`where($id_column, 'in', implode(',', $meta_ids))`
or this:
`where($id_column, 'in', $meta_ids)`

**Comment by emsifa** [comment]
It use array instead of string. 

It will cast non-array type into single array like `["your-value"]`. [(see this)](https://github.com/emsifa/laci-db/blob/master/src/Query.php#L286-L290)
