### ISSUE TITLE
Error on Match Filter

### ISSUE THREAD

**Issue by nomadicjosh** [emsifa/laci-db#8]
When trying to use the match filter, I kept getting the following error:

```"preg_match(): Delimiter must not be alphanumeric or backslash"```

I changed this:

```
case 'match':
$filter = function($row) use ($key, $value) {
return (bool) preg_match($value, $row[$key]);
};
```

to this and it fixed my issue:

```
case 'match':
$filter = function($row) use ($key, $value) {
return (bool) preg_match("/$value/", $row[$key]);
};
```

**Comment by emsifa** [comment]
In match filter, you should put regex delimiter in filter value. So you are able to use regex flags and delimiter type as you want.

**Comment by nomadicjosh** [comment]
Ah, got it. Thanks.
